# Generated by Django 3.1.5 on 2021-01-12 04:10

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect', models.BooleanField(default=False)),
                ('freq', models.IntegerField(default=5)),
                ('pmhigh', models.IntegerField(default=5)),
                ('work_s', models.CharField(max_length=4)),
                ('work_e', models.CharField(max_length=4)),
                ('comment', models.TextField(null=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPM.companys')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPM.companys')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(null=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPM.companys')),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPM.devices')),
            ],
        ),
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pm10', models.IntegerField()),
                ('pm25', models.IntegerField()),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPM.devices')),
            ],
        ),
        migrations.CreateModel(
            name='AvgDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pm10', models.IntegerField()),
                ('pm25', models.IntegerField()),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPM.devices')),
            ],
        ),
    ]
